import { NextRequest, NextResponse } from 'next/server';
import type { GS_Assinatura, GS_Plano } from '@/types/gs/billing';

const mockPlanos: GS_Plano[] = [
  {
    id: 'plano-basico',
    nome: 'Básico',
    slug: 'basico',
    descricao: 'Para ARs em início de operação',
    publico_alvo: 'AR',
    nivel: 'BASICO',
    valor_mensal: 97.00,
    taxa_por_cert: 7.50,
    limite_certs: 50,
    max_usuarios: 3,
    max_unidades: 1,
    max_clientes: 200,
    integracoes: ['ANGRY'],
    suporte_tipo: 'EMAIL',
    recursos: { dashboard: true, api: false, relatorios: false, white_label: false },
    is_active: true,
    ordem: 1,
  },
  {
    id: 'plano-profissional',
    nome: 'Profissional',
    slug: 'profissional',
    descricao: 'Para ARs em crescimento',
    publico_alvo: 'AR',
    nivel: 'PROFISSIONAL',
    valor_mensal: 197.00,
    taxa_por_cert: 5.00,
    limite_certs: 200,
    max_usuarios: 10,
    max_unidades: 3,
    max_clientes: 1000,
    integracoes: ['ANGRY', 'SAFEWEB', 'VALID'],
    suporte_tipo: 'CHAT',
    recursos: { dashboard: true, api: true, relatorios: true, white_label: false },
    is_active: true,
    ordem: 2,
  },
  {
    id: 'plano-enterprise',
    nome: 'Enterprise',
    slug: 'enterprise',
    descricao: 'Para grandes ARs e ACs',
    publico_alvo: 'AR',
    nivel: 'ENTERPRISE',
    valor_mensal: 497.00,
    taxa_por_cert: 3.00,
    limite_certs: -1,
    max_usuarios: -1,
    max_unidades: -1,
    max_clientes: -1,
    integracoes: ['ANGRY', 'SAFEWEB', 'VALID', 'SYNGULAR', 'CERTISIGN'],
    suporte_tipo: 'PRIORITARIO',
    recursos: { dashboard: true, api: true, relatorios: true, white_label: true },
    is_active: true,
    ordem: 3,
  },
];

const mockAssinatura: GS_Assinatura = {
  id: 'assin-001',
  ar_id: 'ar-001',
  contador_id: null,
  entidade_tipo: 'AR',
  plano_id: 'plano-profissional',
  status: 'ATIVA',
  asaas_subscription_id: 'sub_mock_001',
  asaas_customer_id: 'cus_mock_001',
  data_inicio: '2025-01-01',
  data_proximo_ciclo: '2026-08-01',
  data_cancelamento: null,
  ciclo_tipo: 'MENSAL',
  trial_ate: null,
  certs_no_ciclo: 47,
  certs_faturados: 50,
  excedente: 0,
  valor_mensal_cobrado: 197.00,
  split_percent_gs: 10,
  split_percent_ar: 90,
  dias_vencimento: 15,
  plano: mockPlanos[1],
  ar_nome: 'AR Central VEMAPI',
};

export async function GET(_req: NextRequest) {
  return NextResponse.json({
    assinatura: mockAssinatura,
    planos: mockPlanos,
  });
}
